<template>
    <Container>
        <SectionContainer>
            <section>
                <Heading>intonation-trainer</Heading>
            </section>
        </SectionContainer>
    </Container>
</template>
